#!/usr/bin/env bash
# ==============================================================================
# 💎 AXIS-NIDDHI — package_steward_distribution.sh
# Steward Distribution Packager V1.0
# Tier: STEWARD — full rebuild capability
# ==============================================================================
# Produces: releases/steward/
#   pipeline/
#     scripts/core/        ← 34 canonical pipeline scripts
#     scripts/tools/       ← utility scripts
#     metadata/            ← PDPN CSVs, glossary, manifests
#     03-translations/     ← 93 frozen PT-BR translations
#     sources/             ← PureDhamma source ZIP (2.2GB)
#   README_steward.md
#
# EXPLICITLY EXCLUDED:
#   scripts/private/       ← credentials NEVER distributed
#   scripts/legacy/        ← superseded scripts
#   09-csl/                ← regenerated by pipeline
#   13-static-site/        ← regenerated by pipeline
#   13-ssg/__pycache__/    ← generated artifacts
#
# Usage:
#   bash scripts/tools/package_steward_distribution.sh
#   BENG_BASE=/path/to/pipeline bash scripts/tools/package_steward_distribution.sh
# ==============================================================================
set -euo pipefail

_SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
INPUT_BASE="${BENG_BASE:-$(cd "$_SELF_DIR/../.." && pwd)}"
SOURCES_MODE="copy"

usage() {
    cat <<EOF
Usage:
  bash scripts/tools/package_steward_distribution.sh [options]
  BENG_BASE=/path/to/pipeline-or-workspace bash scripts/tools/package_steward_distribution.sh

Options:
  --sources-mode reference|copy Control whether source ZIPs are copied
  --skip-source-copy            Shortcut for --sources-mode reference
  --include-sources             Shortcut for --sources-mode copy
  --sealed-full-copy            Shortcut for --sources-mode copy
  -h, --help                    Show this help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --sources-mode)
            [[ $# -ge 2 ]] || { echo "Missing value for --sources-mode" >&2; usage; exit 1; }
            case "$2" in
                reference|copy)
                    SOURCES_MODE="$2" ;;
                *)
                    echo "Invalid --sources-mode: $2" >&2
                    usage
                    exit 1 ;;
            esac
            shift 2 ;;
        --skip-source-copy)
            SOURCES_MODE="reference"; shift ;;
        --include-sources|--sealed-full-copy)
            SOURCES_MODE="copy"; shift ;;
        -h|--help)
            usage; exit 0 ;;
        *)
            echo "Unknown argument: $1" >&2
            usage
            exit 1 ;;
    esac
done

if [ -d "$INPUT_BASE/scripts/core" ]; then
    PIPELINE_BASE="$INPUT_BASE"
    WORKSPACE_ROOT="$(cd "$INPUT_BASE/.." && pwd)"
elif [ -d "$INPUT_BASE/pipeline/scripts/core" ]; then
    WORKSPACE_ROOT="$INPUT_BASE"
    PIPELINE_BASE="$INPUT_BASE/pipeline"
else
    echo "❌ Could not resolve pipeline base from BENG_BASE=$INPUT_BASE" >&2
    exit 1
fi

SOURCES_ROOT="$WORKSPACE_ROOT/sources"

GREEN='\033[0;32m'
CYAN='\033[0;96m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
GRAY='\033[0;37m'
NC='\033[0m'

RELEASE_DIR="$PIPELINE_BASE/releases/steward"
TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")

write_source_reference_json() {
    local dest_dir="$1"
    local zip_file="$2"
    local mode="$3"
    local size_bytes sha256 generated_at
    size_bytes="$(stat -c '%s' "$zip_file")"
    sha256="$(sha256sum "$zip_file" | awk '{print $1}')"
    generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

    cat > "$dest_dir/source_reference.json" <<EOF
{
  "filename": "$(basename "$zip_file")",
  "canonical_path": "$zip_file",
  "size_bytes": $size_bytes,
  "sha256": "$sha256",
  "generated_at": "$generated_at",
  "mode": "$mode"
}
EOF
}

echo -e "\n${CYAN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  💎 AXIS-NIDDHI — Steward Distribution Packager      ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════╝${NC}"
echo -e "   ${GRAY}Base    : $PIPELINE_BASE${NC}"
echo -e "   ${GRAY}Root    : $WORKSPACE_ROOT${NC}"
echo -e "   ${GRAY}Output  : $RELEASE_DIR${NC}"
echo -e "   ${GRAY}Sources : $SOURCES_MODE${NC}"
echo -e "   ${GRAY}Build   : $TIMESTAMP${NC}\n"

# ==============================================================================
# GUARDS
# ==============================================================================
MISSING=0
for required in \
    "$PIPELINE_BASE/scripts/core" \
    "$PIPELINE_BASE/scripts/tools" \
    "$PIPELINE_BASE/metadata" \
    "$PIPELINE_BASE/03-translations" \
    "$SOURCES_ROOT"; do
    if [ ! -d "$required" ]; then
        echo -e "  ${YELLOW}⚠ Missing: $required${NC}"
        MISSING=$((MISSING+1))
    fi
done

if [ "$MISSING" -gt 0 ]; then
    echo -e "${RED}❌ $MISSING required directories missing. Aborting.${NC}"
    exit 1
fi

# Credentials guard — hard fail if private/ would be included
if ls "$PIPELINE_BASE/scripts/private/"*.txt 2>/dev/null | grep -q .; then
    echo -e "${GREEN}✔ scripts/private/ detected — will be excluded from package${NC}"
fi

# ==============================================================================
# PREPARE OUTPUT
# ==============================================================================
echo -e "  ${GRAY}[1/6] Preparing output directory...${NC}"
rm -rf "$RELEASE_DIR"
mkdir -p "$RELEASE_DIR/pipeline/scripts"
mkdir -p "$RELEASE_DIR/pipeline/metadata"
mkdir -p "$RELEASE_DIR/pipeline/03-translations"
mkdir -p "$RELEASE_DIR/pipeline/sources"
mkdir -p "$RELEASE_DIR/pipeline/13-ssg"

# ==============================================================================
# COPY SCRIPTS/CORE
# ==============================================================================
echo -e "  ${GRAY}[2/6] Copying scripts/core/ (pipeline engine)...${NC}"
rsync -a --quiet \
    "$PIPELINE_BASE/scripts/core/" \
    "$RELEASE_DIR/pipeline/scripts/core/"
CORE_COUNT=$(ls "$RELEASE_DIR/pipeline/scripts/core/" | wc -l)
echo -e "     ${GRAY}$CORE_COUNT files${NC}"

# ==============================================================================
# COPY SCRIPTS/TOOLS (exclude packagers — they reference local paths)
# ==============================================================================
echo -e "  ${GRAY}[3/6] Copying scripts/tools/...${NC}"
rsync -a --quiet \
    "$PIPELINE_BASE/scripts/tools/" \
    "$RELEASE_DIR/pipeline/scripts/tools/"
TOOLS_COUNT=$(ls "$RELEASE_DIR/pipeline/scripts/tools/" | wc -l)
echo -e "     ${GRAY}$TOOLS_COUNT files${NC}"

# ==============================================================================
# COPY METADATA
# ==============================================================================
echo -e "  ${GRAY}[4/6] Copying metadata/...${NC}"
rsync -a --quiet \
    --exclude="*.bak" \
    "$PIPELINE_BASE/metadata/" \
    "$RELEASE_DIR/pipeline/metadata/"
CANON_HASH="UNKNOWN"
if [ -f "$PIPELINE_BASE/metadata/canon_manifest.json" ]; then
    CANON_HASH=$(python3 -c "
import json
d = json.load(open('$PIPELINE_BASE/metadata/canon_manifest.json'))
print(d.get('canon_hash','UNKNOWN'))
" 2>/dev/null || echo "UNKNOWN")
    echo -e "     ${GRAY}canon_manifest.json — hash: ${CANON_HASH:0:24}...${NC}"
fi

# ==============================================================================
# COPY 03-TRANSLATIONS
# ==============================================================================
echo -e "  ${GRAY}[5/6] Copying 03-translations/...${NC}"
rsync -a --quiet \
    "$PIPELINE_BASE/03-translations/" \
    "$RELEASE_DIR/pipeline/03-translations/"
TRANS_COUNT=$(find "$RELEASE_DIR/pipeline/03-translations" -name "pt-BR.html" | wc -l)
echo -e "     ${GRAY}$TRANS_COUNT frozen translations${NC}"

# ==============================================================================
# COPY SOURCES / SOURCE REFERENCE
# ==============================================================================
echo -e "  ${GRAY}[6/6] Recording sources/...${NC}"
LATEST_ZIP=$(find "$SOURCES_ROOT" -maxdepth 1 -name "*.zip" | sort | tail -n 1)
if [ -z "$LATEST_ZIP" ]; then
    echo -e "${RED}❌ No source ZIP found in $SOURCES_ROOT${NC}"
    rm -rf "$RELEASE_DIR"
    exit 1
fi
write_source_reference_json "$RELEASE_DIR/pipeline/sources" "$LATEST_ZIP" "$SOURCES_MODE"
if [ "$SOURCES_MODE" = "copy" ]; then
    find "$SOURCES_ROOT" -maxdepth 1 -name "*.zip" -exec cp {} "$RELEASE_DIR/pipeline/sources/" \;
    ZIP_SIZE=$(du -sh "$RELEASE_DIR/pipeline/sources/" 2>/dev/null | cut -f1)
    echo -e "     ${GRAY}$ZIP_SIZE${NC}"
else
    echo -e "     ${GRAY}reference only — source_reference.json${NC}"
fi

# ==============================================================================
# COPY SSG ENGINE (no __pycache__)
# ==============================================================================
rsync -a --quiet \
    --exclude="__pycache__" \
    --exclude="*.pyc" \
    "$PIPELINE_BASE/13-ssg/" \
    "$RELEASE_DIR/pipeline/13-ssg/"

# ==============================================================================
# CREDENTIALS AUDIT — hard verify
# ==============================================================================
CRED_LEAK=0
for pattern in "deepl_key" "wp_password" "github_token" ".password" ".key" "private/"; do
    if find "$RELEASE_DIR" -name "*${pattern}*" 2>/dev/null | grep -q .; then
        echo -e "  ${RED}❌ CREDENTIAL LEAK DETECTED: $pattern${NC}"
        CRED_LEAK=$((CRED_LEAK+1))
    fi
done

if [ "$CRED_LEAK" -gt 0 ]; then
    echo -e "${RED}❌ ABORTING — credentials detected in package. Package destroyed.${NC}"
    rm -rf "$RELEASE_DIR"
    exit 2
fi
echo -e "  ${GREEN}✔ Credentials audit passed — no private data in package${NC}"

# ==============================================================================
# README
# ==============================================================================
cat > "$RELEASE_DIR/README_steward.md" << README
# PureDhamma — Steward Distribution

**Tier:** STEWARD — Full Rebuild Capability  
**Engine:** AXIS-NIDDHI V5.4  
**Corpus:** PureDhamma — Teachings of Professor Lal  
**Build:** $TIMESTAMP

---

## Purpose

The Steward holds the complete rebuild capability for the PureDhamma canon.  
From this distribution, a Steward can:

- Rebuild the entire corpus from the original source ZIP
- Restore all frozen PT-BR translations
- Generate the static site in any environment
- Maintain and extend the translation workflow

---

## Contents

\`\`\`
steward/
├── pipeline/
│   ├── scripts/
│   │   ├── core/          ← 34 canonical pipeline scripts
│   │   └── tools/         ← utility scripts
│   ├── metadata/          ← PDPN CSVs, glossary, manifests
│   ├── 03-translations/   ← $TRANS_COUNT frozen PT-BR translations
│   ├── sources/           ← source_reference.json + ZIPs (copy mode only)
│   └── 13-ssg/            ← Static site generator engine
└── README_steward.md
\`\`\`

---

## Requirements

- Python 3.12+
- MySQL (for SG extraction phase only)
- packages: \`pip install pandas pymysql beautifulsoup4 requests jinja2\`

---

## Full Rebuild

\`\`\`bash
cd pipeline

# Set base path
export BENG_BASE=\$(pwd)

# Verify integrity (should show 30/30 PASS)
bash scripts/core/verify_pipeline_integrity.sh

# Full rebuild
bash scripts/core/run_full_pipeline.sh --full
\`\`\`

---

## Translation Freeze Workflow

After each DeepL translation session:

\`\`\`bash
# Freeze new translations to 03-translations/
python3 scripts/core/SP00_freeze_translations.py

# On next rebuild, SP01b restores them automatically
\`\`\`

---

## Axis CLI

\`\`\`bash
# Full rebuild
bash scripts/tools/axis_cli.sh build

# Integrity check
bash scripts/tools/axis_cli.sh verify

# Generate canon manifest
bash scripts/tools/axis_cli.sh manifest

# Mission report
bash scripts/tools/axis_cli.sh report

# Serve locally
bash scripts/tools/axis_cli.sh serve
\`\`\`

---

## Canon Manifest

Verify cryptographic integrity:

\`\`\`bash
python3 -c "
import json
m = json.load(open('pipeline/metadata/canon_manifest.json'))
print('Engine :', m['engine'], 'V'+m['engine_version'])
print('CSL    :', m['csl_entries'], 'posts')
print('Transl.:', m['translations_frozen'])
print('Hash   :', m['canon_hash'][:32]+'...')
print('Status :', m['verification'])
"
\`\`\`

---

## Note

\`scripts/private/\` (credentials) is **never included** in any distribution.  
Each Steward must supply their own DeepL key and WordPress credentials.
README

# ==============================================================================
# SIZE REPORT
# ==============================================================================
TOTAL_SIZE=$(du -sh "$RELEASE_DIR" | cut -f1)
PIPELINE_SIZE=$(du -sh "$RELEASE_DIR/pipeline" | cut -f1)

echo ""
echo -e "${GREEN}══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ STEWARD DISTRIBUTION PACKAGED${NC}"
echo -e "══════════════════════════════════════════════════"
echo -e "  ${GRAY}Location     : $RELEASE_DIR${NC}"
echo -e "  ${GRAY}pipeline/    : $PIPELINE_SIZE${NC}"
echo -e "  ${GRAY}Total        : $TOTAL_SIZE${NC}"
echo -e "  ${GRAY}Core scripts : $CORE_COUNT${NC}"
echo -e "  ${GRAY}Translations : $TRANS_COUNT frozen${NC}"
echo -e "  ${GRAY}Canon hash   : ${CANON_HASH:0:24}...${NC}"
echo -e "  ${GRAY}Credentials  : EXCLUDED ✅${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════${NC}\n"
