import pandas as pd
import pymysql
import os
import sys
import re
from datetime import datetime

# ==============================================================================
# 🔱 BRASILEIRINHO ENGINE - FASE 1: EXTRAÇÃO GLOBAL (V3)
# Objetivo: Extrair SRO para a pasta 'en-US' com Nomenclatura Canônica Imutável
# Manual de Referência: Capítulo 15 (Primeiro Documento) & Capítulo 8 (SRO)
# ==============================================================================

# --- CONFIGURAÇÕES ---
BASE_DIR = "/media/sanghop/BrasileirinhoHD/Brasileirinho_Engine_v2/pipeline"
INPUT_CSV = os.path.join(BASE_DIR, "metadata", "PDPN_01_Operational.csv")

# Definindo a Fonte Canônica (SRO)
SOURCE_LANG = "en-US" 
OUTPUT_DIR = os.path.join(BASE_DIR, "01-extracted-htmls", SOURCE_LANG)

# Configuração do Banco
DB_CONFIG = {
    'user': 'root', 'password': '', 'host': 'localhost',
    'database': 'puredhamma_clean',
    'cursorclass': pymysql.cursors.DictCursor
}

def setup_environment():
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        print(f"📁 Diretório SRO criado: {OUTPUT_DIR}")

def detect_table_prefix(conn):
    with conn.cursor() as cursor:
        cursor.execute("SHOW TABLES LIKE '%_posts'")
        result = cursor.fetchone()
        if result:
            table_name = list(result.values())[0]
            return table_name.replace('posts', '')
    sys.exit("❌ Erro: Tabela de posts não encontrada.")

def clean_slug(slug):
    """Sanitiza o slug para ser seguro no sistema de arquivos (Linux/Windows)."""
    if not isinstance(slug, str): return "unknown-slug"
    # Mantém apenas alfanuméricos e hífens. Remove pontos para não confundir extensão.
    slug = re.sub(r'[^a-zA-Z0-9\-]', '', slug)
    return slug.lower()

def generate_tattoo(row):
    """
    Gera a 'Tatuagem Canônica' (Metadata Header) conforme o Manual Cap. 2.
    Isso garante a Anti-Amnésia dentro do próprio arquivo.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""<!--
💎 BRASILEIRINHO ENGINE - CANONICAL SOURCE ARTIFACT
===================================================
Fin-dex:      {row['Fin-dex']}
PD#PN:        {row['PD#PN']}
Original-Slug:{row['Slug_Derived']}
Source-ID:    {row['id_10WEB.io']}
Language:     {SOURCE_LANG}
Extracted-At: {now}
Origin:       SQL Dump (PureDhamma SRO)
===================================================
DO NOT EDIT THIS FILE MANUALLY. THIS IS THE TREASURE.
-->
"""

def main():
    print(f">>> 🚀 INICIANDO EXTRAÇÃO GLOBAL ({SOURCE_LANG})...")
    setup_environment()

    # 1. Carregar Irmã Operacional
    try:
        # dtype=str para preservar zeros à esquerda se houver, e evitar float no ID
        df = pd.read_csv(INPUT_CSV, sep=';', encoding='utf-8', dtype=str)
        
        # Filtragem de Segurança: Só extraímos o que tem ID e PD#PN válido
        df = df[df['id_10WEB.io'].notna() & (df['id_10WEB.io'] != '')]
        print(f"    -> {len(df)} posts mapeados e prontos para extração.")
    except Exception as e:
        print(f"❌ Erro ao ler CSV: {e}")
        return

    # 2. Conectar ao Banco
    try:
        conn = pymysql.connect(**DB_CONFIG)
        prefix = detect_table_prefix(conn)
        table_posts = f"{prefix}posts"
    except Exception as e:
        print(f"❌ Erro SQL: {e}")
        return

    # 3. Extração em Loop
    success_count = 0
    error_count = 0

    print(">>> Extraindo conteúdo do Tesouro...")
    
    with conn.cursor() as cursor:
        for index, row in df.iterrows():
            try:
                wp_id = int(row['id_10WEB.io']) # Garante int para o SQL
                
                # Formatação Rigorosa do Nome
                findex = str(row['Fin-dex']).zfill(4) # 0001
                pdpn = row['PD#PN'].strip()
                slug = clean_slug(row['Slug_Derived'])
                
                # NOME CANÔNICO: [Fin-dex]__[PD#PN]__[Slug].html
                filename = f"{findex}__{pdpn}__{slug}.html"
                filepath = os.path.join(OUTPUT_DIR, filename)

                # Busca o conteúdo
                query = f"SELECT post_content, post_title FROM {table_posts} WHERE ID = %s"
                cursor.execute(query, (wp_id,))
                result = cursor.fetchone()

                if result:
                    content = result['post_content']
                    
                    # Injeta a Tatuagem (Anti-Amnésia)
                    tattoo = generate_tattoo(row)
                    # Adiciona título H1 se não existir (opcional, mas bom para visualização)
                    # Mas conforme Manual (Fase 0/1), devemos preservar o original.
                    # A tatuagem é um comentário, então não altera o render.
                    final_content = tattoo + "\n" + content
                    
                    # Salva o arquivo (UTF-8 forçado)
                    with open(filepath, 'w', encoding='utf-8') as f:
                        f.write(final_content)
                    
                    success_count += 1
                    # Feedback visual discreto a cada 100
                    if success_count % 100 == 0:
                        print(f"    ... {success_count} artefatos preservados.")
                else:
                    print(f"⚠️  ID {wp_id} (Fin-dex {findex}) não encontrado no banco.")
                    error_count += 1

            except Exception as e:
                print(f"❌ Falha no Fin-dex {row.get('Fin-dex', '?')}: {e}")
                error_count += 1

    conn.close()
    print("\n==================================================")
    print(f"✅ EXTRAÇÃO CONCLUÍDA COM SUCESSO!")
    print(f"🏛️  Tesouro Materializado em: {OUTPUT_DIR}")
    print(f"📥 Arquivos Gerados: {success_count}")
    print(f"⚠️  Erros: {error_count}")
    print("==================================================")
    print("Próximo passo sugerido: Validar se a pasta 'en-US' contém os arquivos ordenados.")

if __name__ == "__main__":
    main()
